# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-06 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20181206_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('post_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='categorys',
        ),
        migrations.RemoveField(
            model_name='image',
            name='location',
        ),
        migrations.AlterModelOptions(
            name='categorys',
            options={},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
        migrations.RenameField(
            model_name='categorys',
            old_name='categorys',
            new_name='Category',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='photo',
            name='category',
            field=models.ManyToManyField(default=True, to='photos.Categorys'),
        ),
        migrations.AddField(
            model_name='photo',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.location'),
        ),
    ]
